### ISSUE TITLE
Seed.js when starting a Typescript project

### ISSUE THREAD

**Issue by joeleonard212** [remix-run/indie-stack#113]
### Have you experienced this bug with the latest version of the template?

remix-run/indie-stack blog-tutorial

### Steps to Reproduce

run command:

npx create-remix --template remix-run/indie-stack blog-tutorial

then choose:

Typescript

### Expected Behavior

in the prisma module, should be a file called seed.ts

### Actual Behavior

the actual file is seed.js and some errors are occuring when using it

**Comment by MichaelDeBoey** [comment]
This is probably related to the changes from #106

@joeleonard212 Could you please explain the error that you're seeing?

**Comment by mcansh** [comment]
yeah @joeleonard212 I'm not seeing any issues on a freshly created indie-stack so if there's any specific errors you're seeing that would be helpful https://gist.github.com/mcansh/8e4bfd21f2f8de96ab00989d8aa15154

**Comment by moishinetzer** [comment]
This is probably related to the commit which changed the prisma seed command to use `node` instead of `ts-node` and changed `seed.ts` to `seed.js`.

Could you revert the above changes and see if that fixes anything?

**Comment by flyingwolf1701** [comment]
Hello @moishinetzer I did try and change my code to reflect what you said. Additionally in app/posts/index.tsx I had to replace the first two lines with: 
`import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";`
from 
`const { PrismaClient } = require("@prisma/client");
const bcrypt = require("bcryptjs");`

I think the issue is that the blog tutorial hasn't bee updated. The problem I am getting is: 
`Property 'post' does not exist on type 'PrismaClient<PrismaClientOptions, never, RejectOnNotFound | RejectPerOperation | undefined>'.`
That issue is pointing at:
`  for (const post of posts) {
    await prisma.post.upsert({
      where: { slug: post.slug },
      update: post,
      create: post,
    });
  }`
It doesn't like the post in await prisma.post.upsert. 
I am guessing that the post type in PrismaClientOptions is also screwed up. I am sure this little issue is making a lot of new people turn away from Remix which is a shame because this is pretty amazing stuff.
