### ISSUE TITLE
"Invariant failed" on npm start

### ISSUE THREAD

**Issue by mrkurt** [remix-run/indie-stack#23]
We're getting this error when on `npm start` after a migration command. I don't think there are more stack lines, though. Any idea if this is a misconfig or a bug of some kind?

```Preparing to run: `sh start.sh` as root
 fra [info]+ npx prisma migrate deploy
Datasource "db": SQLite database "sqlite.db" at "file:/data/sqlite.db"
No pending migrations to apply.
+ npm run start
> start
> remix-serve build
/myapp/node_modules/tiny-invariant/dist/tiny-invariant.cjs.js:10
        throw new Error(prefix);
              ^
Error: Invariant failed
    at invariant (/myapp/node_modules/tiny-invariant/dist/tiny-invariant.cjs.js:10:15)
    at Object.<anonymous> (/myapp/build/index.js:443:35)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
```

**Comment by netdesignr** [comment]
@mrkurt thanks for escalating this here. Still no success in overcoming this issue

**Comment by netdesignr** [comment]
@mrkurt ok, now that's weird. All fixed after I've tried re-building a couple of times. You might want to close this issue for now.

**Comment by brian-dlee** [comment]
I'm getting this same exact issue with a freshly created app from Indie stack. If any has any suggestions I'm open. I imagine it's not  Fly related. I've tried changing NPM versions between node:16 node:16-bullseye-slim and node:14 and tried upgrading NPM to the latest with in the Docker container since I figured it could be a minor package version resolution issue difference between my Mac and the linux container. The node:14 container had an issue with the `npx prisma ...` command in start.sh, so it's inconclusive whether or not that would have worked.

**Comment by brian-dlee** [comment]
I found the issue for anyone else who happens upon this. `invariant` is used to check for `SESSION_SECRET` and I did not have a `SESSION_SECRET` secret defined in Fly. Lo and behold, the README outlines this step just fine.

**Comment by alifhaider** [comment]
What to do if I found this issue?

**Comment by machour** [comment]
@alifhaider you fill in a **new** issue with all details possible.
