### ISSUE TITLE
Can not add custom component into index, but works in other route

### ISSUE THREAD

**Issue by shunia** [remix-run/indie-stack#51]
I'm trying something with this template, but meet a wired error which says: 
```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

What I did is just create a custom test component and use it in the index route.

The component itself is like:
```typescript
// app/components/navbar.client.tsx

export default function Navbar() {
  return (<div>Navbar</div>);
}
```

Use it in the index route:
```typescript
// app/routes/index.tsx
import Navbar from "~/components/navbar.client";

export default function Index() {
  console.log(Navbar); // outputs the imported Navbar function

  return (
    <main>
      <Navbar />
    </main>
  );
}
```

If I put the component in other route like login, it is totally fine and just renders. So what did I do wrong? 
Sorry if this is silly, I'm a front end developer not knowing much about server side rendering.

**Comment by kentcdodds** [comment]
Hi @shunia!

The problem is if you add `.client.` to your filename, then it will be `undefined` during the server render which will mean that on the server `<Navbar />` is trying to render `undefined`.

If you have to render this on the client only, the I recommend following the example in https://github.com/remix-run/remix/tree/main/examples/client-only-components

Hope that helps. Good luck!

**Comment by shunia** [comment]
That's obvious, how silly I am. 
Thank you for the explanation.
